os:
    - linux
    - osx
language: generic
sudo: required
dist: trusty

osx_image: xcode8.3
before_install:
    - if [ $TRAVIS_OS_NAME == "osx" ]; then
            brew tap vapor/tap;
            brew update;
            brew install vapor;
            brew install cmysql;
        else
            eval "$(curl -sL https://apt.vapor.sh)";
            sudo apt-get install vapor;
            sudo apt-get install cmysql;
        fi

script:
    - vapor build --verbose
    - vapor build --release --verbose
    - vapor test --verbose
