os:
    - osx
language: generic
sudo: required
dist: trusty

osx_image: xcode8.3
before_install:
    brew tap vapor/tap;
    brew update;
    brew install vapor;
    brew install cmysql;

script:
    - vapor build --verbose
    - vapor build --release --verbose
    - vapor test --verbose
